# Generated by Django 3.2.8 on 2021-10-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_pollingunit_polling_unit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='date_entered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
