# Generated by Django 3.2.8 on 2021-10-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_alter_ward_date_entered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='states',
            new_name='state_name',
        ),
    ]
