# Generated by Django 3.2.8 on 2021-10-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_rename_states_state_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='date_entered',
            field=models.TextField(),
        ),
    ]
