# Generated by Django 3.2.8 on 2021-10-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_alter_lga_date_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcedpuresult',
            name='date_entered',
            field=models.TextField(),
        ),
    ]
