# Generated by Django 3.2.8 on 2021-10-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_alter_announcedpuresult_date_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcedlgaresult',
            name='date_entered',
            field=models.TextField(),
        ),
    ]
