# Generated by Django 3.2.8 on 2021-10-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_alter_announcedlgaresult_date_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentname',
            name='polling_unit',
            field=models.BigIntegerField(),
        ),
    ]
